version: '3'
services:
  myapp-main:
    image: keyin-cody-qap4:latest
    ports:
      - "8080:8080"
    environment:
#      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/spring_2022
      - spring.datasource.url=jdbc:mysql://database-1.c6sktn2y6aq0.us-east-1.rds.amazonaws.com/my_schema
      - spring.datasource.password=Keyin2021
      - spring.datasource.username=admin
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver